M48
; DRILL file {KiCad (6.0.7)} date Mon Sep 26 21:03:12 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-26T21:03:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X101.981Y-105.843
X102.616Y-86.158
X176.276Y-86.158
X176.276Y-105.843
T0
M30
